Implement malaria form with the module
OpenSRP/opensrp-client-chw-malaria pull request #31
Opened 2019-06-08 18:31 UTC by manutarus

2019-06-09 08:10 UTC, ladleo commented
I tried running it crushes before it even starts

2019-06-09 08:11 UTC, whoisladleo requested changes
The app crushes before it even starts

2019-06-09 09:54 UTC, whoisladleo submitted a review, later dismissed

2019-06-10 07:03 UTC, whoisladleo submitted a review, later dismissed

2019-06-11 10:22 UTC, whoisladleo approved these changes

2019-06-11 11:22 UTC, merged